import { ArrowRight, BarChart3, CheckCircle2, CircleAlert, FileWarning, TrendingUp } from 'lucide-react';
import { useMemo } from 'react';
import { Link } from 'wouter';
import { useGetDashboardStats, useGetRecentCredentials } from '@workspace/api-client-react';
import { PageHeader, StatusPill } from '@/components/app-shell';

const fallbackStats = { total: 28, verified: 21, suspicious: 4, invalid: 3, weekly: [{ label: 'Mon', count: 3 }, { label: 'Tue', count: 5 }, { label: 'Wed', count: 2 }, { label: 'Thu', count: 6 }, { label: 'Fri', count: 4 }, { label: 'Sat', count: 3 }, { label: 'Sun', count: 5 }] };
const fallbackRecent = [{ certificateId: 'CTR-DEMO-24017', studentName: 'Elena Marquez', institution: 'Northbridge University', score: 94, status: 'verified', verifiedAt: '2025-02-18T10:42:00.000Z' }, { certificateId: 'CTR-00841', studentName: 'Jon Bell', institution: 'Redwood Institute of Design', score: 67, status: 'suspicious', verifiedAt: '2025-02-17T14:18:00.000Z' }, { certificateId: 'CTR-00838', studentName: 'Priya Shah', institution: 'Lakeshore College', score: 88, status: 'verified', verifiedAt: '2025-02-16T09:06:00.000Z' }];

export default function Dashboard() {
  const statsQuery = useGetDashboardStats();
  const recentQuery = useGetRecentCredentials();
  const stats = statsQuery.data ?? fallbackStats;
  const recent = recentQuery.data ?? fallbackRecent;
  const maxCount = useMemo(() => Math.max(...stats.weekly.map((item) => item.count), 1), [stats.weekly]);
  return <div className="mx-auto max-w-7xl px-5 py-8 md:px-10 md:py-12"><PageHeader eyebrow="Verification activity" title="Keep the thread." description="A lightweight view of the decisions your team has made recently." action={<Link href="/verify" className="inline-flex items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-sm font-semibold text-[hsl(var(--primary-foreground))]" data-testid="link-dashboard-new">New verification <ArrowRight size={15} /></Link>} />
    <div className="mb-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: 'All checks', value: stats.total, icon: BarChart3, color: 'text-[hsl(var(--primary))]' }, { label: 'Verified', value: stats.verified, icon: CheckCircle2, color: 'text-[hsl(161_54%_30%)]' }, { label: 'Needs review', value: stats.suspicious, icon: CircleAlert, color: 'text-[hsl(31_74%_35%)]' }, { label: 'Invalid', value: stats.invalid, icon: FileWarning, color: 'text-[hsl(var(--destructive))]' }].map(({ label, value, icon: Icon, color }) => <div key={label} className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5"><div className="mb-6 flex items-center justify-between"><span className="text-xs text-[hsl(var(--muted-foreground))]">{label}</span><Icon size={17} className={color} /></div><p className="font-display text-5xl leading-none">{value}</p><div className="mt-4 flex items-center gap-1 font-mono-ui text-[10px] text-[hsl(var(--primary))]"><TrendingUp size={12} /> from this workspace</div></div>)}</div>
    <div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 md:p-7"><div className="mb-8 flex items-start justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-[hsl(var(--muted-foreground))]">Volume</p><h2 className="mt-2 text-lg font-semibold">Checks this week</h2></div><span className="rounded-full bg-[hsl(var(--secondary))] px-2.5 py-1 font-mono-ui text-[10px] text-[hsl(var(--muted-foreground))]">7 days</span></div><div className="flex h-48 items-end gap-2.5 border-b border-[hsl(var(--border))] pb-0">{stats.weekly.map((item) => <div key={item.label} className="group flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="font-mono-ui text-[10px] text-[hsl(var(--muted-foreground))] opacity-0 transition-opacity group-hover:opacity-100">{item.count}</span><div className="w-full rounded-t-lg bg-[hsl(var(--primary)/.82)] transition-all group-hover:bg-[hsl(var(--accent))]" style={{ height: `${Math.max(8, item.count / maxCount * 76)}%` }} /><span className="mb-3 font-mono-ui text-[10px] text-[hsl(var(--muted-foreground))]">{item.label}</span></div>)}</div></section><section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 md:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-[hsl(var(--muted-foreground))]">Recent records</p><h2 className="mt-2 text-lg font-semibold">Latest decisions</h2></div><Link href="/verify" className="text-xs font-semibold text-[hsl(var(--primary))]" data-testid="link-dashboard-view-all">Verify another</Link></div><div className="space-y-1">{recent.map((item) => <Link href={`/report/${item.certificateId}`} key={item.certificateId} className="flex items-center gap-3 rounded-xl p-3 transition-colors hover:bg-[hsl(var(--secondary)/.55)]" data-testid={`row-recent-${item.certificateId}`}><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[hsl(var(--secondary))] font-mono-ui text-[10px] text-[hsl(var(--primary))]">{item.studentName.split(' ').map((name) => name[0]).join('').slice(0, 2)}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{item.studentName}</span><span className="block truncate text-xs text-[hsl(var(--muted-foreground))]">{item.institution}</span></span><span className="hidden text-right sm:block"><span className="block font-display text-xl">{item.score}</span><span className="block text-[10px] text-[hsl(var(--muted-foreground))]">score</span></span><StatusPill status={item.status} /></Link>)}</div>{recent.length === 0 && <div className="py-12 text-center text-sm text-[hsl(var(--muted-foreground))]">No decisions yet. Your first check will appear here.</div>}</section></div>
  </div>;
}