import { AlertTriangle, ArrowLeft, Check, Clipboard, ExternalLink, FileKey2, Info, ShieldCheck, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link, useParams } from 'wouter';
import { getGetCredentialQueryKey, useGetCredential, type VerificationReport } from '@workspace/api-client-react';
import { PageHeader, StatusPill } from '@/components/app-shell';
import { demoReport } from '@/lib/credential';

export default function Report() {
  const { certificateId } = useParams<{ certificateId: string }>();
  const localReport = useMemo(() => {
    const raw = sessionStorage.getItem('creditrust-report');
    return raw ? JSON.parse(raw) as VerificationReport : null;
  }, []);
  const reportQuery = useGetCredential(certificateId ?? '', { query: { enabled: !!certificateId, queryKey: getGetCredentialQueryKey(certificateId ?? '') } });
  const report = reportQuery.data ?? localReport ?? (certificateId === demoReport.certificate.certificateId ? demoReport : null);
  const [copied, setCopied] = useState(false);

  async function copyLink() {
    await navigator.clipboard?.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  }

  if (reportQuery.isLoading && !report) return <ReportSkeleton />;
  if (!report) return <div className="mx-auto max-w-3xl px-5 py-16 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[hsl(var(--secondary))]"><FileKey2 size={24} /></span><h1 className="mt-6 font-display text-5xl">Report unavailable.</h1><p className="mt-3 text-sm text-[hsl(var(--muted-foreground))]">This credential may have expired or was not found in the current workspace.</p><Link href="/verify" className="mt-7 inline-flex rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-sm font-semibold text-[hsl(var(--primary-foreground))]" data-testid="link-report-retry">Start another verification</Link></div>;

  const scoreColor = report.score >= 80 ? 'text-[hsl(var(--primary))]' : report.score >= 55 ? 'text-[hsl(28_74%_47%)]' : 'text-[hsl(var(--destructive))]';
  return <div className="mx-auto max-w-6xl px-5 py-8 md:px-10 md:py-12"><div className="mb-5"><Link href="/dashboard" className="inline-flex items-center gap-2 text-xs font-semibold text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]" data-testid="link-report-back"><ArrowLeft size={14} /> Back to activity</Link></div><PageHeader eyebrow="Verification report" title="A decision with receipts." description={`Generated ${new Date(report.timestamp).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })}`} action={<div className="flex gap-2"><button onClick={copyLink} className="inline-flex items-center gap-2 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-3 py-2 text-xs font-semibold" data-testid="button-copy-report"><Clipboard size={14} />{copied ? 'Copied' : 'Copy link'}</button><Link href="/verify" className="inline-flex items-center gap-2 rounded-lg bg-[hsl(var(--primary))] px-3 py-2 text-xs font-semibold text-[hsl(var(--primary-foreground))]" data-testid="link-new-verification">New check <ExternalLink size={13} /></Link></div>} />
    <div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]">
      <section className="space-y-6">
        <div className="relative overflow-hidden rounded-2xl bg-[hsl(var(--sidebar))] p-7 text-[hsl(var(--sidebar-foreground))] md:p-9"><div className="absolute -right-12 -top-16 size-56 rounded-full border-[24px] border-[hsl(var(--sidebar-primary)/.08)]" /><div className="relative flex items-start justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-[hsl(var(--sidebar-foreground)/.55)]">Trust score</p><div className="mt-3 flex items-baseline gap-3"><span className={`font-display text-8xl leading-none ${scoreColor}`}>{report.score}</span><span className="font-mono-ui text-xs text-[hsl(var(--sidebar-foreground)/.48)]">/ 100</span></div></div><StatusPill status={report.status} /></div><div className="mt-8 h-2 overflow-hidden rounded-full bg-[hsl(var(--sidebar-accent))]"><div className={`h-full rounded-full ${report.score >= 80 ? 'bg-[hsl(var(--sidebar-primary))]' : 'bg-[hsl(var(--accent))]'}`} style={{ width: `${report.score}%` }} /></div><p className="mt-6 max-w-lg text-sm leading-6 text-[hsl(var(--sidebar-foreground)/.7)]">{report.explanation[0] ?? 'The score summarizes the strength of available evidence, not a substitute for human review.'}</p></div>
        <div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 md:p-8"><div className="mb-6 flex items-center justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-[hsl(var(--muted-foreground))]">Evidence signals</p><h2 className="mt-2 text-lg font-semibold">Why this score?</h2></div><span className="rounded-full bg-[hsl(var(--secondary))] px-2.5 py-1 font-mono-ui text-[10px] text-[hsl(var(--muted-foreground))]">{report.signals.length} reviewed</span></div><div className="space-y-2">{report.signals.map((signal) => <div key={signal.key} className="rounded-xl border border-[hsl(var(--border))] p-4"><div className="flex items-start gap-3"><span className={`mt-0.5 grid size-7 shrink-0 place-items-center rounded-lg ${signal.status === 'passed' ? 'bg-[hsl(157_42%_89%)] text-[hsl(161_54%_25%)]' : signal.status === 'attention' ? 'bg-[hsl(40_91%_88%)] text-[hsl(31_74%_31%)]' : 'bg-[hsl(4_74%_92%)] text-[hsl(4_61%_37%)]'}`}>{signal.status === 'passed' ? <Check size={14} /> : signal.status === 'attention' ? <Info size={14} /> : <X size={14} />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{signal.label}</p><span className="font-mono-ui text-[10px] text-[hsl(var(--muted-foreground))]">{signal.points ?? 0} / {signal.maxPoints ?? 0}</span></div><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">{signal.detail}</p></div></div></div>)}</div></div>
      </section>
      <aside className="space-y-6"><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6"><p className="mb-5 font-mono-ui text-[10px] uppercase tracking-[.18em] text-[hsl(var(--muted-foreground))]">Credential record</p><div className="space-y-4">{[['Student', report.certificate.studentName], ['Institution', report.certificate.institution], ['Award', report.certificate.degree], ['Registration', report.certificate.registrationNumber], ['Issued', new Date(report.certificate.issueDate).toLocaleDateString(undefined, { dateStyle: 'medium' })]].map(([label, value]) => <div key={label}><p className="text-[10px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div></div><div className="rounded-2xl border border-[hsl(var(--accent)/.4)] bg-[hsl(var(--accent)/.1)] p-6"><div className="flex items-center gap-2 text-sm font-semibold"><AlertTriangle size={16} className="text-[hsl(28_74%_42%)]" /> Reviewer notes</div>{report.findings.length ? <div className="mt-4 space-y-3">{report.findings.map((finding, index) => <div key={`${finding.type}-${index}`}><div className="mb-1 flex items-center justify-between font-mono-ui text-[10px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]"><span>{finding.type}</span><span>{finding.severity}</span></div><p className="text-xs leading-5">{finding.message}</p></div>)}</div> : <p className="mt-3 text-xs leading-5 text-[hsl(var(--muted-foreground))]">No reviewer notes were generated for this record.</p>}</div><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card)/.65)] p-5"><div className="flex items-center gap-2 text-xs font-semibold"><ShieldCheck size={15} className="text-[hsl(var(--primary))]" /> Document fingerprint</div><p className="mt-3 break-all font-mono-ui text-[10px] leading-5 text-[hsl(var(--muted-foreground))]">{report.documentHash}</p><p className="mt-3 text-[10px] leading-4 text-[hsl(var(--muted-foreground))]">A fingerprint helps reviewers confirm which document was assessed.</p></div></aside>
    </div>
  </div>;
}

function ReportSkeleton() {
  return <div className="mx-auto max-w-6xl animate-pulse px-5 py-12 md:px-10"><div className="h-3 w-28 rounded bg-[hsl(var(--secondary))]" /><div className="mt-7 h-14 w-80 rounded bg-[hsl(var(--secondary))]" /><div className="mt-10 grid gap-6 lg:grid-cols-2"><div className="h-64 rounded-2xl bg-[hsl(var(--secondary))]" /><div className="h-64 rounded-2xl bg-[hsl(var(--secondary))]" /></div></div>;
}